### ISSUE TITLE
Recipe Creation Errors Should be displayed on the top of page

### ISSUE THREAD

**Issue by p-sheth** [k-sheth/react-getting-started#14]
1. Add recipe
2. Open In Brief panel, leave decription filed empty
3. Close In Brief Panel
4. Complete rest of the steps
5. Click save and continue

The user is not taken to listing page, but the error -- 'description is required' is not visible. Confusing behavior

**Comment by k-sheth** [comment]
fixed: added alert at top of page with all the errors

**Comment by k-sheth** [comment]
This issue was moved to k-sheth/calendar-khana-lagao#48
