### ISSUE TITLE
In recipe, if cooking method is not added, recipes does not get saved, but no error is displayed to that effect

### ISSUE THREAD

**Issue by p-sheth** [k-sheth/react-getting-started#19]

**Comment by k-sheth** [comment]
fixed: In addition to marking the error on the field, an overall error alert is also shown

**Comment by k-sheth** [comment]
This issue was moved to k-sheth/calendar-khana-lagao#43

**Comment by k-sheth** [comment]
This issue was moved to k-sheth/calendar-khana-lagao#53
